server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            allowedOrigins: "http://localhost:3001"
            allow-credentials: true
            allowedHeaders: "*"
      routes:
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
             - Path=/member/**

        - id: photo-service
          uri: lb://PHOTO-SERVICE
          predicates:
            - Path=/photo/**

        - id: pcomment-service
          uri: lb://PCOMMENT-SERVICE
          predicates:
            - Path=/pComment/**


        - id: home-service
          uri: lb://HOME-SERVICE
          predicates:
            - Path=/home/**
