server:
  port: 9005
spring:
  application:
    name: pcomment-service
  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka