server:
  port: 9008
spring:
  application:
    name: image-service


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
file: C:\Users\klove\Documents\MSA_POSWORLD\MSA_UploadService\uploadService\src\main\resources\static