server:
  port: 9002
spring:
  application:
    name: home-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

mybatis:
  config-location: classpath:config/myBatis.xml
