server:
  port: 9007

spring:
  application:
    name: user-service

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/posworld?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
#    servlet:
#      multipart:
#        max-file-size: 100MB
#        max-request-size: 100MB

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

jwt :
  secret_key: SECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEYSECRETKEY
  expTime: 3600000


token:
  expiration_time: 86400000
  secret: user_token

gateway:
  ip: 127.0.0.1
